/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as CuentaPendienteRouteImport } from './routes/cuenta-pendiente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedBitacoraRouteImport } from './routes/_authed/bitacora'
import { Route as AuthedConfiguracionRouteImport } from './routes/_authed/configuracion'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedMiAsistenciaRouteImport } from './routes/_authed/mi-asistencia'
import { Route as AuthedMiEquipoRouteImport } from './routes/_authed/mi-equipo'
import { Route as AuthedNominaRouteImport } from './routes/_authed/nomina'
import { Route as AuthedReportesRouteImport } from './routes/_authed/reportes'
import { Route as AuthedUsuariosRouteImport } from './routes/_authed/usuarios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaPendienteRoute = CuentaPendienteRouteImport.update({
  id: '/cuenta-pendiente',
  path: '/cuenta-pendiente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBitacoraRoute = AuthedBitacoraRouteImport.update({
  id: '/bitacora',
  path: '/bitacora',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConfiguracionRoute = AuthedConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMiAsistenciaRoute = AuthedMiAsistenciaRouteImport.update({
  id: '/mi-asistencia',
  path: '/mi-asistencia',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMiEquipoRoute = AuthedMiEquipoRouteImport.update({
  id: '/mi-equipo',
  path: '/mi-equipo',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNominaRoute = AuthedNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportesRoute = AuthedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsuariosRoute = AuthedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuenta-pendiente': typeof CuentaPendienteRoute
  '/login': typeof LoginRoute
  '/bitacora': typeof AuthedBitacoraRoute
  '/configuracion': typeof AuthedConfiguracionRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/mi-asistencia': typeof AuthedMiAsistenciaRoute
  '/mi-equipo': typeof AuthedMiEquipoRoute
  '/nomina': typeof AuthedNominaRoute
  '/reportes': typeof AuthedReportesRoute
  '/usuarios': typeof AuthedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuenta-pendiente': typeof CuentaPendienteRoute
  '/login': typeof LoginRoute
  '/bitacora': typeof AuthedBitacoraRoute
  '/configuracion': typeof AuthedConfiguracionRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/mi-asistencia': typeof AuthedMiAsistenciaRoute
  '/mi-equipo': typeof AuthedMiEquipoRoute
  '/nomina': typeof AuthedNominaRoute
  '/reportes': typeof AuthedReportesRoute
  '/usuarios': typeof AuthedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/cuenta-pendiente': typeof CuentaPendienteRoute
  '/login': typeof LoginRoute
  '/_authed/bitacora': typeof AuthedBitacoraRoute
  '/_authed/configuracion': typeof AuthedConfiguracionRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/mi-asistencia': typeof AuthedMiAsistenciaRoute
  '/_authed/mi-equipo': typeof AuthedMiEquipoRoute
  '/_authed/nomina': typeof AuthedNominaRoute
  '/_authed/reportes': typeof AuthedReportesRoute
  '/_authed/usuarios': typeof AuthedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuenta-pendiente'
    | '/login'
    | '/bitacora'
    | '/configuracion'
    | '/dashboard'
    | '/mi-asistencia'
    | '/mi-equipo'
    | '/nomina'
    | '/reportes'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuenta-pendiente'
    | '/login'
    | '/bitacora'
    | '/configuracion'
    | '/dashboard'
    | '/mi-asistencia'
    | '/mi-equipo'
    | '/nomina'
    | '/reportes'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/cuenta-pendiente'
    | '/login'
    | '/_authed/bitacora'
    | '/_authed/configuracion'
    | '/_authed/dashboard'
    | '/_authed/mi-asistencia'
    | '/_authed/mi-equipo'
    | '/_authed/nomina'
    | '/_authed/reportes'
    | '/_authed/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  CuentaPendienteRoute: typeof CuentaPendienteRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta-pendiente': {
      id: '/cuenta-pendiente'
      path: '/cuenta-pendiente'
      fullPath: '/cuenta-pendiente'
      preLoaderRoute: typeof CuentaPendienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/bitacora': {
      id: '/_authed/bitacora'
      path: '/bitacora'
      fullPath: '/bitacora'
      preLoaderRoute: typeof AuthedBitacoraRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/configuracion': {
      id: '/_authed/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthedConfiguracionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/mi-asistencia': {
      id: '/_authed/mi-asistencia'
      path: '/mi-asistencia'
      fullPath: '/mi-asistencia'
      preLoaderRoute: typeof AuthedMiAsistenciaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/mi-equipo': {
      id: '/_authed/mi-equipo'
      path: '/mi-equipo'
      fullPath: '/mi-equipo'
      preLoaderRoute: typeof AuthedMiEquipoRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nomina': {
      id: '/_authed/nomina'
      path: '/nomina'
      fullPath: '/nomina'
      preLoaderRoute: typeof AuthedNominaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reportes': {
      id: '/_authed/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthedReportesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/usuarios': {
      id: '/_authed/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthedUsuariosRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedBitacoraRoute: typeof AuthedBitacoraRoute
  AuthedConfiguracionRoute: typeof AuthedConfiguracionRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMiAsistenciaRoute: typeof AuthedMiAsistenciaRoute
  AuthedMiEquipoRoute: typeof AuthedMiEquipoRoute
  AuthedNominaRoute: typeof AuthedNominaRoute
  AuthedReportesRoute: typeof AuthedReportesRoute
  AuthedUsuariosRoute: typeof AuthedUsuariosRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedBitacoraRoute: AuthedBitacoraRoute,
  AuthedConfiguracionRoute: AuthedConfiguracionRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMiAsistenciaRoute: AuthedMiAsistenciaRoute,
  AuthedMiEquipoRoute: AuthedMiEquipoRoute,
  AuthedNominaRoute: AuthedNominaRoute,
  AuthedReportesRoute: AuthedReportesRoute,
  AuthedUsuariosRoute: AuthedUsuariosRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  CuentaPendienteRoute: CuentaPendienteRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
