/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PendingAccountRouteImport } from './routes/pending-account'
import { Route as AuthedAttendanceRouteImport } from './routes/_authed/attendance'
import { Route as AuthedClockInRouteImport } from './routes/_authed/clock-in'
import { Route as AuthedDailyRouteImport } from './routes/_authed/daily'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDepartmentsRouteImport } from './routes/_authed/departments'
import { Route as AuthedGpsRouteImport } from './routes/_authed/gps'
import { Route as AuthedIncidentsRouteImport } from './routes/_authed/incidents'
import { Route as AuthedLogsRouteImport } from './routes/_authed/logs'
import { Route as AuthedPayrollRouteImport } from './routes/_authed/payroll'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedReportsRouteImport } from './routes/_authed/reports'
import { Route as AuthedRestDaysRouteImport } from './routes/_authed/rest-days'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedTeamRouteImport } from './routes/_authed/team'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingAccountRoute = PendingAccountRouteImport.update({
  id: '/pending-account',
  path: '/pending-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAttendanceRoute = AuthedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClockInRoute = AuthedClockInRouteImport.update({
  id: '/clock-in',
  path: '/clock-in',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDailyRoute = AuthedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDepartmentsRoute = AuthedDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGpsRoute = AuthedGpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedIncidentsRoute = AuthedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogsRoute = AuthedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPayrollRoute = AuthedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReportsRoute = AuthedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRestDaysRoute = AuthedRestDaysRouteImport.update({
  id: '/rest-days',
  path: '/rest-days',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTeamRoute = AuthedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-account': typeof PendingAccountRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/clock-in': typeof AuthedClockInRoute
  '/daily': typeof AuthedDailyRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/departments': typeof AuthedDepartmentsRoute
  '/gps': typeof AuthedGpsRoute
  '/incidents': typeof AuthedIncidentsRoute
  '/logs': typeof AuthedLogsRoute
  '/payroll': typeof AuthedPayrollRoute
  '/profile': typeof AuthedProfileRoute
  '/reports': typeof AuthedReportsRoute
  '/rest-days': typeof AuthedRestDaysRoute
  '/settings': typeof AuthedSettingsRoute
  '/team': typeof AuthedTeamRoute
  '/users': typeof AuthedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending-account': typeof PendingAccountRoute
  '/attendance': typeof AuthedAttendanceRoute
  '/clock-in': typeof AuthedClockInRoute
  '/daily': typeof AuthedDailyRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/departments': typeof AuthedDepartmentsRoute
  '/gps': typeof AuthedGpsRoute
  '/incidents': typeof AuthedIncidentsRoute
  '/logs': typeof AuthedLogsRoute
  '/payroll': typeof AuthedPayrollRoute
  '/profile': typeof AuthedProfileRoute
  '/reports': typeof AuthedReportsRoute
  '/rest-days': typeof AuthedRestDaysRoute
  '/settings': typeof AuthedSettingsRoute
  '/team': typeof AuthedTeamRoute
  '/users': typeof AuthedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending-account': typeof PendingAccountRoute
  '/_authed/attendance': typeof AuthedAttendanceRoute
  '/_authed/clock-in': typeof AuthedClockInRoute
  '/_authed/daily': typeof AuthedDailyRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/departments': typeof AuthedDepartmentsRoute
  '/_authed/gps': typeof AuthedGpsRoute
  '/_authed/incidents': typeof AuthedIncidentsRoute
  '/_authed/logs': typeof AuthedLogsRoute
  '/_authed/payroll': typeof AuthedPayrollRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/rest-days': typeof AuthedRestDaysRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/team': typeof AuthedTeamRoute
  '/_authed/users': typeof AuthedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending-account'
    | '/attendance'
    | '/clock-in'
    | '/daily'
    | '/dashboard'
    | '/departments'
    | '/gps'
    | '/incidents'
    | '/logs'
    | '/payroll'
    | '/profile'
    | '/reports'
    | '/rest-days'
    | '/settings'
    | '/team'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending-account'
    | '/attendance'
    | '/clock-in'
    | '/daily'
    | '/dashboard'
    | '/departments'
    | '/gps'
    | '/incidents'
    | '/logs'
    | '/payroll'
    | '/profile'
    | '/reports'
    | '/rest-days'
    | '/settings'
    | '/team'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/pending-account'
    | '/_authed/attendance'
    | '/_authed/clock-in'
    | '/_authed/daily'
    | '/_authed/dashboard'
    | '/_authed/departments'
    | '/_authed/gps'
    | '/_authed/incidents'
    | '/_authed/logs'
    | '/_authed/payroll'
    | '/_authed/profile'
    | '/_authed/reports'
    | '/_authed/rest-days'
    | '/_authed/settings'
    | '/_authed/team'
    | '/_authed/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingAccountRoute: typeof PendingAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-account': {
      id: '/pending-account'
      path: '/pending-account'
      fullPath: '/pending-account'
      preLoaderRoute: typeof PendingAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/attendance': {
      id: '/_authed/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthedAttendanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clock-in': {
      id: '/_authed/clock-in'
      path: '/clock-in'
      fullPath: '/clock-in'
      preLoaderRoute: typeof AuthedClockInRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/daily': {
      id: '/_authed/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthedDailyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/departments': {
      id: '/_authed/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthedDepartmentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/gps': {
      id: '/_authed/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof AuthedGpsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/incidents': {
      id: '/_authed/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthedIncidentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/logs': {
      id: '/_authed/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthedLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payroll': {
      id: '/_authed/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthedPayrollRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rest-days': {
      id: '/_authed/rest-days'
      path: '/rest-days'
      fullPath: '/rest-days'
      preLoaderRoute: typeof AuthedRestDaysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/team': {
      id: '/_authed/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthedTeamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAttendanceRoute: typeof AuthedAttendanceRoute
  AuthedClockInRoute: typeof AuthedClockInRoute
  AuthedDailyRoute: typeof AuthedDailyRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDepartmentsRoute: typeof AuthedDepartmentsRoute
  AuthedGpsRoute: typeof AuthedGpsRoute
  AuthedIncidentsRoute: typeof AuthedIncidentsRoute
  AuthedLogsRoute: typeof AuthedLogsRoute
  AuthedPayrollRoute: typeof AuthedPayrollRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedRestDaysRoute: typeof AuthedRestDaysRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTeamRoute: typeof AuthedTeamRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAttendanceRoute: AuthedAttendanceRoute,
  AuthedClockInRoute: AuthedClockInRoute,
  AuthedDailyRoute: AuthedDailyRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDepartmentsRoute: AuthedDepartmentsRoute,
  AuthedGpsRoute: AuthedGpsRoute,
  AuthedIncidentsRoute: AuthedIncidentsRoute,
  AuthedLogsRoute: AuthedLogsRoute,
  AuthedPayrollRoute: AuthedPayrollRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedRestDaysRoute: AuthedRestDaysRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTeamRoute: AuthedTeamRoute,
  AuthedUsersRoute: AuthedUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingAccountRoute: PendingAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
